<?php

class ExcelGenerator
{

    public function generate($dataInsert,$date_cutoff,$logger)
    {
        $objPHPExcel = new PHPExcel();

        # Set document properties
        $objPHPExcel->getProperties()->setCreator('senangPay')
            ->setLastModifiedBy('senangPay')
            ->setTitle("senangPay Payment to Merchant Report")
            ->setSubject("Payment to Merchant Report")
            ->setDescription("This is a payment to merchant report generated by senangPay")
            ->setKeywords("senangPay Payment to Merchant")
            ->setCategory("Payment");

        # Add the table header
        $objPHPExcel->setActiveSheetIndex(0)
            ->setCellValue('A1', 'Merchant ID')
            ->setCellValue('B1', 'Merchant Name')
            ->setCellValue('C1', 'Document Status')
            ->setCellValue('D1', 'Email')
            ->setCellValue('E1', 'Business Name')
            ->setCellValue('F1', 'Bank')
            ->setCellValue('G1', 'Bank Account Name')
            ->setCellValue('H1', 'Bank Account No')
            ->setCellValue('I1', 'From Date (Midnight of)')
            ->setCellValue('J1', 'Cut-off Date (Midnight of)')
            ->setCellValue('K1', 'Gross Amount (RM)')
            ->setCellValue('L1', 'MDR Amount (RM)')
            ->setCellValue('M1', 'GST Amount (RM)')
            ->setCellValue('N1', 'Unpaid Charges (RM)')
            ->setCellValue('O1', 'Nett Amount (RM)')
            ->setCellValue('P1', 'Details');

        # apply some style to the header cell
        $style_header = array(
            'fill' => array(
                'type' => \PHPExcel_Style_Fill::FILL_SOLID,
                'color' => array('rgb' => '58D3F7'),
            ),
            'font' => array('bold' => true)
        );
        $objPHPExcel->setActiveSheetIndex(0)->getStyle('A1:AQ1')->applyFromArray($style_header);

        # insert the data
        $line_counter = 2;
        foreach ($dataInsert as $payment_info_array) {
            $detailsData = array();
            $detailsData = '';
            foreach ($payment_info_array['details'] as $details) {
                $logger->info('details: ' . json_encode($details));
                $detailsData .= isset($details['source']) ? $details['payment_type'] . '(' . $details['source'] . ')' :
                    $details['payment_type'];
                $detailsData .= "\n" . "TOTAL: " . $details['total'];
                $detailsData .= " | " . "GROSS: RM " . $details['gross_profit'];
                $detailsData .= " | " . "MDR: RM " . $details['total_mdr'];
                $detailsData .= " | " . "NETT: RM " . $details['nett_total'];
                // $detailsData .= "\n"."TRANSACTION REFS: ".$details['transaction_references'];
                $detailsData .= "\n" . "TRANSACTION DATES: " . $details['transaction_dates'];
                $detailsData .= "\n\n";
            }


            $objPHPExcel->setActiveSheetIndex(0)
                ->setCellValue('A' . $line_counter, '' . $payment_info_array['merchant_code'])
                ->setCellValue('B' . $line_counter, $payment_info_array['name'])
                ->setCellValue('C' . $line_counter, $payment_info_array['doc_status'])
                ->setCellValue('D' . $line_counter, $payment_info_array['header_email'])
                ->setCellValue('E' . $line_counter, $payment_info_array['header_name'])
                ->setCellValue('F' . $line_counter, $payment_info_array['bank_name'])
                ->setCellValue('G' . $line_counter, $payment_info_array['bank_account_name'])
                ->setCellValue('H' . $line_counter, 'Acc No: ' . $payment_info_array['bank_account_no'])
                ->setCellValue('I' . $line_counter, $payment_info_array['last_payment_date'])
                ->setCellValue('J' . $line_counter, date('d-M-y', $date_cutoff))
                ->setCellValue('K' . $line_counter, $payment_info_array['gross_profit'])
                ->setCellValue('L' . $line_counter, $payment_info_array['fee'])
                ->setCellValue('M' . $line_counter, $payment_info_array['gst'])
                ->setCellValue('N' . $line_counter, $payment_info_array['unpaid_charges'])
                ->setCellValue('O' . $line_counter, $payment_info_array['amount'])
                ->setCellValue('P' . $line_counter, ($detailsData));

            $line_counter++;
        }

        # format teh bank account no cell as text
        $range = 'G2:' . 'G' . $line_counter;
        $objPHPExcel->getActiveSheet()
            ->getStyle($range)
            ->getNumberFormat()
            ->setFormatCode(\PHPExcel_Style_NumberFormat::FORMAT_TEXT);

        # Rename worksheet
        $objPHPExcel->getActiveSheet()->setTitle('Eligible for Settlement');

        # Set active sheet index to the first sheet, so Excel opens this as the first sheet
        $objPHPExcel->setActiveSheetIndex(0);

        $objWriter = \PHPExcel_IOFactory::createWriter($objPHPExcel, 'Excel2007');

        $file_name = '/tmp/Cutoff_' . date("d_m_Y", $date_cutoff) . '_Eligible_List_' . str_replace(' ', '_', 'All') .
            '_new.xlsx';
        $objWriter->save($file_name);

        return $file_name;
    }
}