name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Install PHP dependencies
      run: composer install --no-dev --optimize-autoloader

    - name: Deploy to Alibaba Cloud Function Compute
      uses: aliyun/serverless-deploy-action@v1
      with:
        region: <region>
        accessKeyId: ${{ secrets.ACCESS_KEY_ID }}
        accessKeySecret: ${{ secrets.ACCESS_KEY_SECRET }}
        serviceName: <service_name>
        functionName: <function_name>
        artifact: .
