name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@
      
    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '7.2' # Set the PHP version here

    - name: Install PHP dependencies
      run: composer install --no-dev --optimize-autoloader

    - name: Deploy to Alibaba Cloud Function Compute
      uses: htynkn/aliyun-serverless-action@master
      env:
        ACCOUNT_ID: ${{ secrets.ALIYUN_ACCOUNT_ID }}
        REGION: ap-southeast-3
        ACCESS_KEY_ID: ${{ secrets.ALIYUN_ACCESS_KEY_ID }}
        ACCESS_KEY_SECRET: ${{ secrets.ALIYUN_ACCESS_KEY_SECRET }}
