name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  serverless-devs-cd:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '7.2'

    - name: Install PHP dependencies
      run: composer install --no-dev --optimize-autoloader
      
    - uses: actions/setup-node@v2
      with:
        node-version: 15
        registry-url: https://registry.npmjs.org/
    - run: npm install
    - run: npm install -g @serverless-devs/s
      # The default key configuration command is an Alibaba Cloud key configuration command. For more information, see the following topics:
      # Use GitHub Actions and Serverless Devs to implement CI/CD: http://short.devsapp.cn/cicd/github/action/usage
      # The official website of Serverless Devs is deployed by using Serverless Devs: http://short.devsapp.cn/cicd/github/action/practice
    - run: s config add --AccountID ${{secrets.ALIYUN_ACCOUNT_ID}} --AccessKeyID ${{secrets.ALIYUN_ACCESS_KEY_ID}} --AccessKeySecret ${{secrets.ALIYUN_ACCESS_KEY_SECRET}} -a default
    # - run: s build
    # - run: rm -rf ./abc
    - run: s deploy --use-local   
