name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Install PHP dependencies
      run: composer install --no-dev --optimize-autoloader

    - name: Deploy to Alibaba Cloud Function Compute
      uses: aliyun/serverless-deploy-action@v1
      with:
        region: ap-southeast-3
        accessKeyId: ${{ secrets.ALIYUN_ACCESS_KEY_ID }}
        accessKeySecret: ${{ secrets.ALIYUN_ACCESS_KEY_SECRET }}
        serviceName: test
        functionName: func-jaf7ifca
        artifact: .
